module.exports = {
  docsSidebar: [
    {
      type: "doc",
      label: "Introduction",
      id: "intro",
    },
    "quickstart",
    "changelog",
  ],

  apiSidebar: [
    {
      type: "autogenerated",
      dirName: "api",
    },
  ],
};
